export const CATEGORIES = [
    'Category:Actors from Alabama',
    'Category:Actors from Alaska',
    'Category:Actors from Arizona',
    'Category:Actors from Arkansas',
    'Category:Actors from California',
    'Category:Actors from Colorado',
    'Category:Actors from Connecticut',
    'Category:Actors from Delaware',
    'Category:Actors from Florida',
    'Category:Actors from Georgia (U.S. state)',
    'Category:Actors from Hawaii',
    'Category:Actors from Idaho',
    'Category:Actors from Illinois',
    'Category:Actors from Indiana',
    'Category:Actors from Iowa',
    'Category:Actors from Kansas',
    'Category:Actors from Kentucky',
    'Category:Actors from Louisiana',
    'Category:Actors from Maine',
    'Category:Actors from Maryland',
    'Category:Actors from Massachusetts',
    'Category:Actors from Michigan',
    'Category:Actors from Minnesota',
    'Category:Actors from Mississippi',
    'Category:Actors from Missouri',
    'Category:Actors from Montana',
    'Category:Actors from Nebraska',
    'Category:Actors from Nevada',
    'Category:Actors from New Hampshire',
    'Category:Actors from New Jersey',
    'Category:Actors from New Mexico',
    'Category:Actors from New York (state)',
    'Category:Actors from North Carolina',
    'Category:Actors from North Dakota',
    'Category:Actors from Ohio',
    'Category:Actors from Oklahoma',
    'Category:Actors from Oregon',
    'Category:Actors from Pennsylvania',
    'Category:Actors from Rhode Island',
    'Category:Actors from South Carolina',
    'Category:Actors from South Dakota',
    'Category:Actors from Tennessee',
    'Category:Actors from Texas',
    'Category:Actors from Utah',
    'Category:Actors from Vermont',
    'Category:Actors from Virginia',
    'Category:Actors from Washington (state)',
    'Category:Actors from West Virginia',
    'Category:Actors from Wisconsin',
    'Category:Actors from Wyoming',
    'Category:American actresses by medium',
    'Category:Lists_of_actors_by_nationality',
    'Category:Lists_of_musicians_by_nationality',
    'Category:Lists_of_singers_by_nationality',
    'Category:Lists_of_athletes_by_nationality',
    'Category:American_men\'s_basketball_players',
    'Category:American_women\'s_basketball_players'
] as const;
